name: Capstone Task Template
description: Structured task tracking for development workflow based on task/INDIVIDUAL_DEVELOPMENT_APPROACH.md
title: "[Phase] - [Feature Name]"
projects: ["lkviray-strat/1"]
assignees:
  - "lkviray-strat"
labels: ["needs-triage"]
body:
  - type: dropdown
    attributes:
      label: Priority
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true

  - type: input
    attributes:
      label: Estimated Time (hrs)
      description: In hours (use 0.5 for 30 mins)
      placeholder: "2.5"
    validations:
      required: true

  - type: input
    attributes:
      label: Target Week
      description: Week number for implementation
      placeholder: "Week 5"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Category
      options:
        - "Setup"
        - "Frontend"
        - "Backend"
        - "Database"
        - "Testing"
        - "Deployment"
        - "Documentation"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Clear description of what needs to be implemented
      placeholder: |
        As a [user role] 
        I want [feature] 
        So that [benefit]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: "Specific, measurable criteria for task completion"
      placeholder: |
        - [ ] Criteria 1
        - [ ] Testing requirements
        - [ ] Performance expectations
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Notes
      description: "Technical approach, dependencies, and resources"
      placeholder: |
        Technical Approach:
        - Architecture decisions

        Dependencies:
        - [Other Task #]

        Resources:
        - [Documentation Link](url)

  - type: checkboxes
    attributes:
      label: Definition of Done
      options:
        - label: Code written and working locally
        - label: Self-reviewed for quality and best practices
        - label: Tests written (if applicable)
        - label: Documentation updated
        - label: Feature deployed and tested
        - label: Ready for optional peer review

  - type: textarea
    attributes:
      label: Additional Context
      description: Screenshots, references, or related issues
